Web/Areas/Admin/Controllers/DoiController.cs
using Application.Interfaces;
using Application.Models;
using Domain.Enums;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Web.Controllers;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DoiController : BaseController
    {
        private readonly IDoiDauService _doiDauService;

        public DoiController(IDoiDauService doiDauService)
        {
            _doiDauService = doiDauService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var result = await _doiDauService.GetAllDoiDau(GiaiDauId);
                return View(result);
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

        [HttpGet]
        public async Task<IActionResult> ChiTiet(int id)
        {
            try
            {
                var result = await _doiDauService.ChiTietDoiDau(id);
                return View(result);
            }
            catch (Exception e)
            {
                return View("Error");
            }
        }
        public IActionResult ThemMoi()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> TaoDoiDau(DoiDauThanhVienModel model)
        {
            bool check = false;
            try
            {
                check = await _doiDauService.TaoDoiDau(GiaiDauId, model);
            }
            catch (Exception e)
            {

            }
            return Json(check);
        }

        [HttpPost]
        public async Task<JsonResult> SuaDoiDau(int id, DoiDauThanhVienModel model)
        {
            bool check = false;
            try
            {
                check = await _doiDauService.SuaDoiDau(id, model);
            }
            catch (Exception e)
            {

            }
            return Json(check);
        }

        [HttpPost]
        public async Task<JsonResult> XoaThanhVien(int id)
        {
            bool check = false;
            try
            {
                check = await _doiDauService.XoaThanhVien(id);
            }
            catch (Exception e)
            {

            }
            return Json(check);
        }

        [HttpPost]
        public async Task<JsonResult> XoaDoiDau(int id)
        {
            bool check = false;
            try
            {
                check = await _doiDauService.XoaDoiDau(id);
            }
            catch (Exception e)
            {

            }
            return Json(check);
        }
    }
}

Web/Areas/Admin/Views/Doi/Index.cshtml
@model List<Application.Models.DoiDauModel>
<style>
    .team-card {
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s ease;
    }

        .team-card:hover {
            transform: translateY(-5px);
        }

    .team-logo {
        height: 8rem;
    }

    .blue-header {
        background-color: #1565c0;
        color: white;
        padding: 6px;
        text-align: center;
    }

    .team-badge {
        min-width: 3rem;
        padding: 0 6px;
        text-align: center;
        font-size: .75rem;
        line-height: 22px;
        height: 22px;
        color: white;
        border-radius: 15px;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
        min-width: 3.2rem;
        padding: 0.2rem 0.4rem;
    }

    .card .card-content {
        padding: 12px;
    }

    .card .card-action {
        padding: 6px;
    }

    .search-wrapper {
        color: #777;
        margin-top: -1px;
        border-top: 1px solid rgba(0, 0, 0, 0.14);
        -webkit-transition: margin .25s ease;
        transition: margin .25s ease;
        position: relative;
    }

        .search-wrapper.focused .search-results:not(:empty) {
            border-bottom: 1px solid rgba(0, 0, 0, 0.14)
        }

        .search-wrapper input#search {
            color: #777;
            display: block;
            font-size: 16px;
            font-weight: 300;
            width: 100%;
            height: 46px;
            margin: 0;
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
            padding: 0 45px 0 0px;
            border: 0
        }

            .search-wrapper input#search:focus {
                outline: none;
                -webkit-box-shadow: none;
                box-shadow: none
            }

        .search-wrapper i.material-icons {
            position: absolute;
            top: 21px;
            right: 10px;
            cursor: pointer
        }

    .search-results {
        margin: 0;
        border-top: 1px solid rgba(0, 0, 0, 0.14);
        background-color: #fff
    }
</style>


<div id="admin_doi_index">
    
    <div class="row right-align">
        <div class="col s12 l4 valign-wrapper" style="height: 62px;">
            <div>
                <a asp-area="Admin" asp-controller="Doi" asp-action="ThemMoi" class="btn-floating" v-on:click="addNewRow">
                    <i class="material-icons">add</i>
                </a>
                Thêm đội đấu
            </div>
        </div>
        <div class="col s12 l4 valign-wrapper" style="height: 62px;">
            <div class="center-align">Có tất cả 1 đội</div>
        </div>
        <div class="col s12 l4">
            <div class="search-wrapper">
                <input id="search" placeholder="Search"><i class="material-icons">search</i>
                <div class="search-results"></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div v-for="(doiDau, index) in doiDaus" :key="index" class="col s12 m6 l3">
            <div class="card team-card">
                <div class="blue-header">
                    <h6>{{doiDau.tenDoiDau}}</h6>
                </div>
                <div class="card-content center">
                    <img onerror="this.onerror=null; this.src='/images/no-image.jpeg';" src="doiDau.linkAvatar" class="avatar-logo team-logo" alt="Atletico Madrid">
                    <div><label>{{doiDau.soTranDaChoi}} trận đã chơi</label></div>
                    <div>
                        <span class="team-badge blue accent-2">{{doiDau.soTranThang}} Thắng</span>
                        <span class="team-badge lime darken-3">{{doiDau.soTranHoa}} Hòa</span>
                        <span class="team-badge grey darken-1">{{doiDau.soTranThua}} Thua</span>
                    </div>
                    <div><label>{{doiDau.soThanhVien}} thành viên</label></div>
                </div>
                <div class="card-action center">
                    <a :href="`/Admin/Doi/ChiTiet/${doiDau.id}`" class="blue darken-3 btn">Chi tiết</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    const data = @Html.Raw(Json.Serialize(Model));
    const { createApp, ref, onMounted,reactive  } = Vue;
    const app = createApp({
        setup() {
            const doiDaus = reactive(data);
            console.log('data',data);
            onMounted(() => {
            });
            return { doiDaus };
        }
    });
    app.mount('#admin_doi_index');
</script>